services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOTLIST_ME_CLIENT_TOKEN=${BOTLIST_ME_CLIENT_TOKEN}
      - DECLARE_SLASH_COMMANDS=${DECLARE_SLASH_COMMANDS}
      - DISCORD_BOTS_GG_TOKEN=${DISCORD_BOTS_GG_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_TOKEN=${DISCORD_CLIENT_TOKEN}
      - DISCORD_LIST_CLIENT_TOKEN=${DISCORD_LIST_CLIENT_TOKEN}
      # - TOPGG_CLIENT_TOKEN=${TOPGG_CLIENT_TOKEN}  # Not needed locally
    volumes:
      - .:/app
    working_dir: /app
